### ISSUE TITLE
Compile Error: "This project is only compatible with Particle system firmware v0.5.3 or later"

### ISSUE THREAD

**Issue by lpercifield** [particle-iot/particle-dev#225]
Hello all,
I'm getting an error that prevents me from compiling code for the Redbear Duo board. After I initially start the Particle Dev IDE, I can compile my code targeting Photon without issue. If I target Redbear Duo, it will compile only once, then throw the error:
<img width="515" alt="screen shot 2017-09-21 at 8 37 56 am" src="https://user-images.githubusercontent.com/595643/30696295-1efb2c24-9ea9-11e7-97f8-468cdb9d40b8.png">
If I restart the IDE and compile for Photon then for Redbear Duo, it will again work, but only once.

<img width="234" alt="screen shot 2017-09-21 at 8 42 03 am" src="https://user-images.githubusercontent.com/595643/30696325-420bf9b4-9ea9-11e7-9328-4eac468c60df.png">

Happy to provide more specifics if needed.

Thanks, and keep up the good work

**Comment by suda** [comment]
Hi! This check is triggered when you're using libraries in Dev. It should be performed only for Particle devices and not compounds. We'll fix it asap

**Comment by knud** [comment]
Hmmm, this seems still to be a problem, at least for me. But perhaps it's a bit different because what I do to get around it is to select a Photon as the device, but the Duo as the target. Compiling works in that case. Then I change devices back to my Duo and flash. This is all via the desktop IDE.

Any idea what's going on? Same problem as above?

**Comment by maiiku** [comment]
@suda Any updates on this? I just tried to migrate from could particle IDE to desktop particle IDE due to lack of git support by cloud particle IDE. I found info that if I need to use git I need to switch to desktop IDE. So I manually copy-pasted all the files into the project, and... I get this error, and @knud's workaround doesn't work for me.

**Comment by suda** [comment]
Unfortunately, there are no updates yet but I'll do my best to tackle it this sprint!

**Comment by maiiku** [comment]
@suda Ok, please keep me posted :) It would be very nice if I could use your desktop IDE :)

**Comment by suda** [comment]
We've just released `particle-dev` package with a fix for this issue. Note: this is only available if you're installed Particle Dev as [an Atom package](https://github.com/particle-iot/particle-dev#github-atom). We're working on updating the standalone package as well.

**Comment by maiiku** [comment]
@suda I can confirm it is indeed working with the particle-dev package (I installed that package manually). Thanks for getting that fix out 👍 

![image](https://user-images.githubusercontent.com/1031355/34850941-34ccc760-f728-11e7-82e2-834956563164.png)
